# Generated by Django 2.2.1 on 2019-06-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190601_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='brithday',
        ),
    ]
