# Generated by Django 2.2.1 on 2019-06-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_beneficiary_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='image',
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='image',
            field=models.ImageField(upload_to='home/images/'),
        ),
    ]
