# Generated by Django 2.2.1 on 2019-06-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190601_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='image',
            field=models.ImageField(default='null', upload_to='home/images/'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='status',
            field=models.BooleanField(verbose_name='모집 중'),
        ),
    ]
