# Generated by Django 2.2.1 on 2019-06-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190601_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='notice',
            field=models.BooleanField(default=1, verbose_name='긴급'),
            preserve_default=False,
        ),
    ]
