# Generated by Django 2.2.1 on 2019-06-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_beneficiary_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='notice',
        ),
    ]
