# Generated by Django 2.2.1 on 2019-06-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_beneficiary_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='notice',
            field=models.BooleanField(default=0, verbose_name='긴급'),
            preserve_default=False,
        ),
    ]
