# Generated by Django 2.2.1 on 2019-06-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_beneficiary_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='need',
            field=models.IntegerField(default=0),
        ),
    ]
