# Generated by Django 2.2.1 on 2019-06-01 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_beneficiary_need'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='title',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='sup_en',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='sup_st',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='vol_en',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='vol_st',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='need',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='people',
            field=models.IntegerField(default=0),
        ),
    ]
