# Generated by Django 2.2.1 on 2019-06-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190602_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='notice',
            field=models.BooleanField(default=0, verbose_name='긴급'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='status',
            field=models.BooleanField(default=0, verbose_name='모집 중'),
        ),
    ]
